### ISSUE TITLE
Manage grades

### ISSUE THREAD

**Issue by maidmaid** [6-5/6-5#10]
- [x] Add grade constants in ``User`` entity:
```php
User::GRADE_RECRUIT = 'recruit'
User::GRADE_SOLDIER = 'soldier'
...
```
- [x] Add grade translations for ``fr``, ``de``, ``it`` and ``en`` locales:
```
// grade.fr.xlf
recruit => 'recrue'
recruit.abbr => 'recr'
soldier => 'soldat'
soldier.abbr => 'sdt'
...
```
- [x] Create an user manager that manage grades: 
```php
UserManager::__construct(Translator $translator, RequestStack $requestStack)
UserManager::getGrades($abbreviated = false, $locale = null)
// return ['recruit' => 'Recrue', 'soldier' => 'soldat']
UserManager::getFullname(User $user, $abbreviated = false, $locale = null)
// return 'soldat Maillard Dany'
```
- [x] Define user manager as service named ``app.user_manager``.
- [x] Test the user manager: 
```php
UserManagerTest::setUp()
UserManagerTest::testGetFullname()
UserManagerTest::getFullnameProvider()
UserManagerTest::testGetGrades()
UserManagerTest::getGradesProvider()
```
- [x] Update ``grade`` field type in ``ReportType`` by using ``UserManager::getGrades()``,
- [x] Update fixtures by using ``UserManager::getGrades()``,

**Comment by CrumbleZ** [comment]
To add the military ranks in the `User` entity, I could use the wiki page that lists english equivalents (https://en.wikipedia.org/wiki/Military_ranks_of_the_Swiss_Armed_Forces) or go for a literal translation. What do you think is best ?
